# Generated by Django 5.2.5 on 2025-08-29 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("courses", "0003_remove_course_created_at_course_teacher_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessment",
            old_name="total_marks",
            new_name="max_score",
        ),
        migrations.AlterField(
            model_name="assessment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="courses.course",
            ),
        ),
    ]
