# Generated by Django 5.2.5 on 2025-08-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_student_created_at_student_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="student",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="updated_at",
        ),
    ]
