# Generated by Django 5.2.5 on 2025-08-29 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_student_created_at_remove_student_date_joined_and_more",
        ),
        ("courses", "0002_course_created_at_alter_course_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="created_at",
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
    ]
